version: '3.9'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        HTML_DIR: $HTML_DIR
    ports:
    - $WEB_PORT:80
    volumes:
    - ./web/html:/usr/share/nginx/html