version: '3.9'
services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: c5dev2_nginx
    container_name: c5dev2_nginx
    restart: unless-stopped
    ports:
      - 8080:80